[package]
name = "marine_vessel_simulator"
version = "0.1.0"
license = "GNU GPLv3"
edition = "2024"
description = "A simulator for marine vessels and their performance in various conditions."
repository = ""

[dependencies]
csv = "1.3.1"
geo = "0.30.0"
uom = "0.36.0"
year-helper = "0.2.1"

